language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  - "pip install --upgrade pip"
  - "pip install ."
  - "pip install pytest mock"
script: py.test
after_success:
  py.test
